# dotnet-test.yml
name: Reusable workflow for running tests in .NET

on: 
  workflow_call:
    inputs: 
      dotnet-version:
        required: true
        type: string
      test-project:
        required: true
        type: string
      verbosity:
        required: false
        type: string
        default: normal

jobs:
  build_and_run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Build image
        run: |
          docker build -t ${{ env.REPOSITORY_NAME }} -f ./apps/dotnetAPI/Dockerfile .
          docker tag ${{ env.REPOSITORY_NAME }}:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPOSITORY_NAME }}:latest

